### ISSUE TITLE
Playback controls disappear after fullscreening the window

### ISSUE THREAD

**Issue by bertob** [celluloid-player/celluloid#824]
Steps to Reproduce:
1. Play a video with the app
2. Click the fullscreen button, all the controls hide after a timeout
3. Move the cursor again, headerbar re-appears, but not the playback controls at the bottom
4. Try to un-fullscreen, playback controls still don't re-appear

Expected Results:

The controls should re-appear on mouse movement in both fullscreen and windowed mode.

Version: 0.24 from Flathub

**Comment by gnome-mpv** [comment]
Probably fixed in 2b24bd3605c009fc87f843b287394976129613b6. Would you be able to test the git version to confirm?

**Comment by bertob** [comment]
Just tried building it, still happens on `eeaabcf460c8e0a29d48d731aec55283bfac04a9` for me.

**Comment by gnome-mpv** [comment]
Hmm. I can't reproduce this at all.

Does the controls re-appear if you press Ctrl+H before moving the cursor?

**Comment by bertob** [comment]
> Does the controls re-appear if you press Ctrl+H before moving the cursor?

Yeah, that fixes it, I didn't know that was a thing. I guess maybe the Ctrl+H behavior is triggered while fullscreening somehow? 

By the way, I wonder if it makes sense to have this shortcut now that the controls are overlay? If we're showing the headerbar on mouse movement anyway we might as well show the playback controls too maybe...

**Comment by gnome-mpv** [comment]
Yeah, I guess it doesn't make much sense anymore. I'll go ahead and remove the shortcut. I'll keep the settings in dconf for now in case someone still wants to permanently hide the controls.
