### ISSUE TITLE
Playback state and window size reset when closing preferences

### ISSUE THREAD

**Issue by jannuary** [celluloid-player/celluloid#956]
Overview Description:
When closing the preferences window, Celluloid changes its window size and rewinds to some other point

Steps to Reproduce:
1. Watch or seek a video to a certain point
2. Fullscreen or maximise the window
3. Enter and leave preferences

Actual Results:
The window unmaximises and the video gets rewinded to an earlier point.
Expected Results:
Quiting preferences doesn't change the window size or playback state.

Version: 0.26

**Comment by gnome-mpv** [comment]
Should be fixed in the git version.

I'll make a new release soon.

**Comment by jannuary** [comment]
Window state is still getting reset on mainline, though unsure about playback since that doesn't seem consistently reproducable.

**Comment by gnome-mpv** [comment]
> Or not? Doesn't seem to be a problem now? Odd.

Did you change any settings when that happened? Some settings change require an mpv reset to work reliably, so if any of those are changed, both playback and window state will still get reset. Just opening/closing the prefs dialog shouldn't do anything though.

**Comment by jannuary** [comment]
Ah, that must be it — changing the configs still unfullscreens the app. That said, it probably shouldn't jump around in any case :)
