### ISSUE TITLE
Playback position not always saved when closing window via close button

### ISSUE THREAD

**Issue by FusionGold** [celluloid-player/celluloid#981]
Overview Description:
When using an external MPV configuration with save-position-on-quit = yes, the video playback position is consistently saved when quitting with the q key. However, when closing the window by clicking the "close" button, the playback position is not always saved. 

Steps to Reproduce:
1. Open a video with save-position-on-quit = yes enabled in external mpv config file.
2. Click to seek to a specific position in the video.
3. Close the window using the "close" button instead of the q key.

Actual Results:
Playback position is not always saved when closing the window using the "close" button.

Expected Results:
Playback position should be saved consistently when closing the window, just as it is when quitting with the q key.

Version:
0.27 (installed via Arch's extra repo)

Additional Information:
Running Arch Linux, GNOME.

**Comment by gnome-mpv** [comment]
Would you be able to test with the git version? I think this might have been fixed already.

**Comment by FusionGold** [comment]
Thank you for your response. I installed the celluloid-git package from AUR, version 0.27.r35.g8356432-1, but unfortunately, the issue still persists.

**Comment by FusionGold** [comment]
Dear dev,
I'm afraid the issue has not been resolved. I tested with [3f2aef9](https://github.com/celluloid-player/celluloid/commit/3f2aef9d829bd99f3db11c000126bf1cccd2fee0)  (installed via celluloid-git), but the problem still persists.
For test, I used a single line configuration in my mpv.conf that is `save-position-on-quit = yes` and did choose the file correctly. Disable loading of file and add `--save-position-on-quit` in the Extra MPV Options UI also not working.

**Comment by gnome-mpv** [comment]
Can you try reproducing the bug again with [logging enabled](https://github.com/celluloid-player/celluloid/blob/master/.github/CONTRIBUTING.md) and post the log file here?

**Comment by FusionGold** [comment]
I have a video file called video_for_test.mkv, and i play it for 3-5 seconds, and then close it.
alias test='rm ~/.config/celluloid/watch_later/*; rm /tmp/celluloid.log;G_MESSAGES_DEBUG=all celluloid video_for_test.mkv --mpv-msg-level=all=trace &> /tmp/celluloid.log'
test with click close button:
[close_button.log](https://github.com/user-attachments/files/17199334/close_button.log)
now, do 'cat ~/.config/celluloid/watch_later/*':
# redirect entry
# redirect entry
test with press q:
[q.log](https://github.com/user-attachments/files/17199335/q.log)
now, do 'cat ~/.config/celluloid/watch_later/*':

**Comment by gnome-mpv** [comment]
Is `close_button_stderr.log` from when it failed to write a watch_later file?

https://github.com/celluloid-player/celluloid/commit/3f2aef9d829bd99f3db11c000126bf1cccd2fee0 fixed a crash on exit that could prevent the watch_later file from being written, but it doesn't look like there's a crash happening in your log. I'm unable to reproduce the bug with the fix applied.

**Comment by FusionGold** [comment]
Yes, for the `close_button_stderr.log` case, I immediately ran `cat ~/.config/celluloid/watch_later/*`, and it showed `# redirect entry # redirect entry` with no time logged. It's wired. Not sure if it's an OS specific issue, a Btrfs filesystem problem, or just an isolated case.

**Comment by FusionGold** [comment]
> if it's an OS specific issue

Can confirm no such issue with the flatpak version. The issue only exists when using the celluloid package from arch extra repo, or using celluloid-git from aur.

**Comment by rthery** [comment]
I'm experiencing the same on 0.27 on a freshly installed Ubuntu 24.10, both with the snap and the ppa:xuzhen666/gnome-mpv versions
I have to use `q` for the position to save, closing with the application with the GUI close button won't save the last position

**Comment by s-h-a-d-o-w** [comment]
I wanted to note two observations that haven't been mentioned so far (using celluloid 0.21, as included with Mint):

1. Saving the position with the close button works when watching continuously from the start but not when skipping ahead. (So: Watch 10 seconds, close, will resume at 10 seconds. But if you then skip ahead a minute and close, it'll still resume from ~10 seconds.)
2. `mpv 0.37.0-1ubuntu4` has no such issues.

(Can confirm that the celluloid workaround of quitting by pressing "q" still works.)
